const CommunityAlert = require("../models/CommunityAlert");

// GET all alerts (active first)
exports.getAlerts = async (req, res) => {
  try {
    const filter = {};
    if (req.query.active === "true")  filter.active = true;
    if (req.query.active === "false") filter.active = false;
    const alerts = await CommunityAlert.find(filter).sort({ active:-1, createdAt:-1 }).lean();
    res.json(alerts);
  } catch(e) { res.status(500).json({ message: e.message }); }
};

// POST create alert (Operator/Admin)
exports.createAlert = async (req, res) => {
  try {
    const { type, title, message, severity, location, radius, instructions, emergencyRef } = req.body;
    if (!type || !title || !message)
      return res.status(400).json({ message: "type, title, message required" });

    const alert = await CommunityAlert.create({
      type, title, message,
      severity: severity || "Medium",
      location: location || {},
      radius:   radius   || 2,
      instructions: Array.isArray(instructions) ? instructions : [],
      createdBy: req.user?.name || req.user?.role || "Operator",
      emergencyRef: emergencyRef || null,
      active: true,
    });

    const io = req.app.get("io");
    io?.emit("communityAlert", alert);
    // also broadcast to operators room
    io?.to("operators").emit("newCommunityAlert", alert);

    res.status(201).json(alert);
  } catch(e) { res.status(500).json({ message: e.message }); }
};

// PATCH resolve alert
exports.resolveAlert = async (req, res) => {
  try {
    const alert = await CommunityAlert.findByIdAndUpdate(
      req.params.id,
      { active: false, resolvedAt: new Date(), resolvedBy: req.user?.name || req.user?.role || "Operator" },
      { new: true }
    );
    if (!alert) return res.status(404).json({ message: "Alert not found" });

    const io = req.app.get("io");
    io?.emit("alertResolved", alert._id);

    res.json(alert);
  } catch(e) { res.status(500).json({ message: e.message }); }
};

// DELETE alert
exports.deleteAlert = async (req, res) => {
  try {
    await CommunityAlert.findByIdAndDelete(req.params.id);
    res.json({ message: "Deleted" });
  } catch(e) { res.status(500).json({ message: e.message }); }
};

// ── AI PREDICTION ALERT GENERATOR ──────────────────────────
exports.generatePredictionAlerts = async (req, res) => {
  try {
    const Emergency = require("../models/Emergency");
    const ai        = require("../ml/aiServices");
    const prediction= require("../ml/predictionModel");
    const weather   = require("../services/weatherService");
    const CommunityAlert = require("../models/CommunityAlert");

    const [emergencies] = await Promise.all([Emergency.find().lean()]);
    const wx = await weather.getWeather(22.7196, 75.8577).catch(()=>null);

    const model = prediction.buildTimeSeriesModel(emergencies);
    const preds = prediction.generatePredictions(model);

    const aiAlerts = ai.generateAutoAlerts(emergencies, preds, wx);
    const saved = [];

    for (const a of aiAlerts) {
      // Check if similar alert already exists (avoid duplicates)
      const existing = await CommunityAlert.findOne({
        title: a.title,
        createdAt: { $gte: new Date(Date.now() - 3600000) } // within last hour
      });
      if (existing) continue;

      // Map AI types to valid model enum values
      const TYPE_MAP = {
        Surge:"Other", Critical:"Other", Prediction:"Other",
        Weather:"Weather", Medical:"Medical", Fire:"Fire",
        Accident:"Accident", Flood:"Flood", Crime:"Crime",
        Traffic:"Traffic", Breakdown:"Breakdown", "Gas Leak":"Gas Leak",
      };
      const alert = await CommunityAlert.create({
        title:        a.title,
        message:      a.message,
        type:         TYPE_MAP[a.type] || "Other",
        severity:     a.severity || "Medium",
        instructions: a.instructions || [],
        issuedBy:     req.user?.name || "AI System",
        issuedById:   req.user?.id,
        autoGenerated:true,
        expiresAt:    new Date(Date.now() + 2 * 3600000), // 2hr expiry
      });
      saved.push(alert);
    }

    res.json({
      message: `Generated ${saved.length} new AI alerts`,
      alerts:  saved,
      analyzed:{ emergencies:emergencies.length, predictions:preds.length, weather:wx?.condition }
    });
  } catch(e) {
    console.error("prediction alert gen:", e);
    res.status(500).json({ error: e.message });
  }
};
