const mongoose = require("mongoose");

const communityAlertSchema = new mongoose.Schema({
  type: {
    type: String,
    enum: ["Accident","Flood","Fire","Traffic","Crime","Gas Leak","Weather","Medical","Breakdown","Other"],
    required: true,
  },
  title:    { type: String, required: true, maxlength: 200 },
  message:  { type: String, required: true, maxlength: 1000 },
  severity: { type: String, enum: ["High","Medium","Low","Info"], default: "Medium" },
  active:   { type: Boolean, default: true },
  location: {
    lat:     Number,
    lng:     Number,
    address: { type: String, default: "" },
    city:    { type: String, default: "" },
    area:    { type: String, default: "" },
    road:    { type: String, default: "" },
  },
  radius:       { type: Number, default: 2 },    // km
  instructions:   [{ type: String }],
  autoGenerated:  { type: Boolean, default: false },
  expiresAt:      { type: Date },
  issuedBy:       { type: String, default: "Operator" },
  issuedById:     { type: String },
  createdBy:    { type: String, default: "Operator" },
  resolvedAt:   Date,
  resolvedBy:   String,
  emergencyRef: { type: mongoose.Schema.Types.ObjectId, ref: "Emergency", default: null },
}, { timestamps: true });

communityAlertSchema.index({ active: 1, createdAt: -1 });
module.exports = mongoose.model("CommunityAlert", communityAlertSchema);
